[package]
name = "klaus"
version = "0.1.0"
edition = "2024"

[features]
default = []
reqwest = ["dep:reqwest"]

[dependencies]
reqwest = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
