# Configuration file for the claus examples
# Copy this file to config.toml and replace the placeholder values with your actual API keys

# Your Anthropic API key for Claude access (REQUIRED for all examples)
# Get this from: https://console.anthropic.com/
anthropic_api_key = "sk-ant-api03-your-anthropic-api-key-here"

# Your Brave Search API key for web search functionality (ONLY needed for assistant example)
# Get this from: https://api.search.brave.com/
brave_api_key = "your-brave-search-api-key-here" 