name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    
    - name: Check
      run: nix-shell --run "./check.sh"
    
    - name: Build
      run: nix-shell --run "./build.sh"
    
    - name: Test
      run: nix-shell --run "./test.sh" 